// src/lib/components/job-detail/tabs/ConfigurationTab.svelte
<script lang="ts">
  import type { JobInfo } from '../../../types/api';
  import { mockNAMDConfig, mockSlurmConfig } from '../../../test/fixtures/mockJobData';

  export let job: JobInfo;
  export let isDemoMode: boolean = false;

  // Display configuration types that include both real fields and demo-only fields
  type DisplayNAMDConfig = {
    simulationSteps: number;
    temperature: number;
    timestep: number;
    outputName: string;
    dcdFreq: number;
    restartFreq: number;
    // Demo-only fields (not in actual NAMDConfig type)
    coordinates?: string;
    structure?: string;
    parameters?: string[];
    cutoff?: number;
    switchDist?: number;
    pairlistDist?: number;
    PME?: boolean;
    PMEGridSpacing?: number;
    langevin?: boolean;
    langevinDamping?: number;
    langevinTemp?: number;
    langevinHydrogen?: boolean;
    useGroupPressure?: boolean;
    useFlexibleCell?: boolean;
    useConstantArea?: boolean;
    langevinPiston?: boolean;
    langevinPistonTarget?: number;
    langevinPistonPeriod?: number;
    langevinPistonDecay?: number;
    langevinPistonTemp?: number;
  };

  type DisplaySlurmConfig = {
    cores: number;
    memory: string;
    wallTime: string;
    partition: string;
    qos: string;
    // Demo-only fields (not in actual SlurmConfig type)
    account?: string;
    nodes?: number;
    tasksPerNode?: number;
    cpusPerTask?: number;
    gpus?: number;
    gpuType?: string;
  };

  // Use imported mock configs from fixtures
  const demoNamdConfig = mockNAMDConfig;
  const demoSlurmConfig = mockSlurmConfig;

  // Get configuration based on mode - using explicit types to satisfy TypeScript
  let namdConfig: DisplayNAMDConfig;
  $: namdConfig = isDemoMode ? demoNamdConfig : {
    simulationSteps: job.namd_config.steps,
    temperature: job.namd_config.temperature,
    timestep: job.namd_config.timestep,
    outputName: job.namd_config.outputname,
    dcdFreq: job.namd_config.dcd_freq || 0,
    restartFreq: job.namd_config.restart_freq || 0,
  };

  let slurmConfig: DisplaySlurmConfig;
  $: slurmConfig = isDemoMode ? demoSlurmConfig : {
    cores: job.slurm_config.cores,
    memory: job.slurm_config.memory,
    wallTime: job.slurm_config.walltime,
    partition: job.slurm_config.partition || 'N/A',
    qos: job.slurm_config.qos || 'N/A',
  };
</script>

<div class="namd-tab-panel">
  <div class="configuration-content">
    <!-- NAMD Configuration -->
    <div class="config-section">
      <h3>NAMD Configuration</h3>

      <!-- Basic Settings -->
      <div class="config-subsection">
        <h4>Simulation Settings</h4>
        <div class="config-grid-3">
          <div class="config-item">
            <div class="config-label">Simulation Steps</div>
            <div class="config-value">{namdConfig.simulationSteps.toLocaleString()}</div>
          </div>
          <div class="config-item">
            <div class="config-label">Temperature (K)</div>
            <div class="config-value">{namdConfig.temperature}</div>
          </div>
          <div class="config-item">
            <div class="config-label">Timestep (fs)</div>
            <div class="config-value">{namdConfig.timestep}</div>
          </div>
          <div class="config-item">
            <div class="config-label">Output Name</div>
            <div class="config-value">{namdConfig.outputName}</div>
          </div>
          <div class="config-item">
            <div class="config-label">DCD Frequency</div>
            <div class="config-value">{namdConfig.dcdFreq > 0 ? namdConfig.dcdFreq.toLocaleString() : 'Not set'}</div>
          </div>
          <div class="config-item">
            <div class="config-label">Restart Frequency</div>
            <div class="config-value">{namdConfig.restartFreq > 0 ? namdConfig.restartFreq.toLocaleString() : 'Not set'}</div>
          </div>
        </div>
      </div>

      {#if isDemoMode}
      <!-- Input Files (Demo mode only - shows detailed NAMD config) -->
      <div class="config-subsection">
        <h4>Input Files</h4>
        <div class="input-files-config">
          <div class="input-file-item">
            <span class="input-file-label">Coordinates:</span>
            <span class="input-file-value">{namdConfig.coordinates ?? 'N/A'}</span>
          </div>
          <div class="input-file-item">
            <span class="input-file-label">Structure:</span>
            <span class="input-file-value">{namdConfig.structure ?? 'N/A'}</span>
          </div>
          <div class="input-file-item">
            <span class="input-file-label">Parameters:</span>
            <div class="parameter-badges">
              {#each (namdConfig.parameters ?? []) as param}
                <span class="parameter-badge">{param}</span>
              {/each}
            </div>
          </div>
        </div>
      </div>

      <!-- Force Field & Cutoffs (Demo mode only) -->
      <div class="config-subsection">
        <h4>Force Field & Cutoffs</h4>
        <div class="config-grid-3">
          <div class="config-item">
            <div class="config-label">Cutoff (Å)</div>
            <div class="config-value">{namdConfig.cutoff ?? 'N/A'}</div>
          </div>
          <div class="config-item">
            <div class="config-label">Switch Distance (Å)</div>
            <div class="config-value">{namdConfig.switchDist ?? 'N/A'}</div>
          </div>
          <div class="config-item">
            <div class="config-label">Pairlist Distance (Å)</div>
            <div class="config-value">{namdConfig.pairlistDist ?? 'N/A'}</div>
          </div>
          <div class="config-item">
            <div class="config-label">PME</div>
            <div class="config-badge {namdConfig.PME ? 'enabled' : 'disabled'}">
              {namdConfig.PME ? 'Enabled' : 'Disabled'}
            </div>
          </div>
          <div class="config-item">
            <div class="config-label">PME Grid Spacing (Å)</div>
            <div class="config-value">{namdConfig.PMEGridSpacing ?? 'N/A'}</div>
          </div>
        </div>
      </div>

      <!-- Dynamics Settings (Demo mode only) -->
      <div class="config-subsection">
        <h4>Dynamics Settings</h4>
        <div class="config-grid-3">
          <div class="config-item">
            <div class="config-label">Langevin Dynamics</div>
            <div class="config-badge {namdConfig.langevin ? 'enabled' : 'disabled'}">
              {namdConfig.langevin ? 'Enabled' : 'Disabled'}
            </div>
          </div>
          <div class="config-item">
            <div class="config-label">Langevin Damping</div>
            <div class="config-value">{namdConfig.langevinDamping ?? 'N/A'} ps⁻¹</div>
          </div>
          <div class="config-item">
            <div class="config-label">Langevin Temperature (K)</div>
            <div class="config-value">{namdConfig.langevinTemp ?? 'N/A'}</div>
          </div>
          <div class="config-item">
            <div class="config-label">Langevin Hydrogen</div>
            <div class="config-badge {namdConfig.langevinHydrogen ? 'enabled' : 'disabled'}">
              {namdConfig.langevinHydrogen ? 'Enabled' : 'Disabled'}
            </div>
          </div>
        </div>
      </div>

      <!-- Pressure Control (Demo mode only) -->
      <div class="config-subsection">
        <h4>Pressure Control</h4>
        <div class="config-grid-3">
          <div class="config-item">
            <div class="config-label">Langevin Piston</div>
            <div class="config-badge {namdConfig.langevinPiston ? 'enabled' : 'disabled'}">
              {namdConfig.langevinPiston ? 'Enabled' : 'Disabled'}
            </div>
          </div>
          <div class="config-item">
            <div class="config-label">Target Pressure (bar)</div>
            <div class="config-value">{namdConfig.langevinPistonTarget ?? 'N/A'}</div>
          </div>
          <div class="config-item">
            <div class="config-label">Piston Period (fs)</div>
            <div class="config-value">{namdConfig.langevinPistonPeriod ?? 'N/A'}</div>
          </div>
          <div class="config-item">
            <div class="config-label">Piston Decay (fs)</div>
            <div class="config-value">{namdConfig.langevinPistonDecay ?? 'N/A'}</div>
          </div>
          <div class="config-item">
            <div class="config-label">Piston Temperature (K)</div>
            <div class="config-value">{namdConfig.langevinPistonTemp ?? 'N/A'}</div>
          </div>
        </div>
      </div>
      {/if}
    </div>

    <!-- SLURM Configuration -->
    <div class="config-section">
      <h3>SLURM Resource Allocation</h3>
      <div class="config-grid-3">
        <div class="config-item">
          <div class="config-label">Cores</div>
          <div class="config-value">{slurmConfig.cores}</div>
        </div>
        <div class="config-item">
          <div class="config-label">Memory</div>
          <div class="config-value">{slurmConfig.memory}</div>
        </div>
        <div class="config-item">
          <div class="config-label">Wall Time</div>
          <div class="config-value">{slurmConfig.wallTime}</div>
        </div>
        <div class="config-item">
          <div class="config-label">Partition</div>
          <div class="config-value">{slurmConfig.partition}</div>
        </div>
        <div class="config-item">
          <div class="config-label">QOS</div>
          <div class="config-value">{slurmConfig.qos}</div>
        </div>
        {#if isDemoMode}
        <!-- Demo-only fields (not in actual SlurmConfig type) -->
        <div class="config-item">
          <div class="config-label">Account</div>
          <div class="config-value">{slurmConfig.account ?? 'N/A'}</div>
        </div>
        <div class="config-item">
          <div class="config-label">Nodes</div>
          <div class="config-value">{slurmConfig.nodes ?? 'N/A'}</div>
        </div>
        <div class="config-item">
          <div class="config-label">Tasks per Node</div>
          <div class="config-value">{slurmConfig.tasksPerNode ?? 'N/A'}</div>
        </div>
        <div class="config-item">
          <div class="config-label">CPUs per Task</div>
          <div class="config-value">{slurmConfig.cpusPerTask ?? 'N/A'}</div>
        </div>
        <div class="config-item">
          <div class="config-label">GPUs</div>
          <div class="config-value">{slurmConfig.gpus ?? 0} × {slurmConfig.gpuType?.toUpperCase() ?? 'N/A'}</div>
        </div>
        {/if}
      </div>
    </div>
  </div>
</div>

// docs/design_mockup/src/components/job-detail/tabs/ConfigurationTab.tsx
import { Job } from "../../../App";
import { Card, CardContent, CardHeader, CardTitle } from "../../ui/card";
import { Badge } from "../../ui/badge";

interface ConfigurationTabProps {
  job: Job;
}

// Mock configuration data
const namdConfig = {
  simulationSteps: 1000000,
  temperature: 310.0,
  timestep: 2.0,
  outputName: "protein_simulation",
  dcdFreq: 5000,
  restartFreq: 10000,
  coordinates: "protein.pdb",
  structure: "protein.psf",
  parameters: ["par_all36_prot.prm", "par_all36_lipid.prm", "toppar_water_ions.str"],
  cutoff: 12.0,
  switchDist: 10.0,
  pairlistDist: 14.0,
  PME: true,
  PMEGridSpacing: 1.0,
  langevin: true,
  langevinDamping: 1.0,
  langevinTemp: 310.0,
  langevinHydrogen: false,
  useGroupPressure: true,
  useFlexibleCell: false,
  useConstantArea: false,
  langevinPiston: true,
  langevinPistonTarget: 1.01325,
  langevinPistonPeriod: 100.0,
  langevinPistonDecay: 50.0,
  langevinPistonTemp: 310.0
};

const slurmConfig = {
  cores: 128,
  memory: "512GB",
  wallTime: "04:00:00",
  partition: "amilan",
  qos: "normal",
  account: "research",
  nodes: 4,
  tasksPerNode: 32,
  cpusPerTask: 1,
  gpus: 4,
  gpuType: "v100"
};

export function ConfigurationTab({ job }: ConfigurationTabProps) {
  return (
    <div className="space-y-6">
      {/* NAMD Configuration */}
      <Card>
        <CardHeader>
          <CardTitle>NAMD Configuration</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Basic Settings */}
          <div>
            <h4 className="font-medium mb-3">Basic Settings</h4>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4 text-sm">
              <div>
                <div className="text-muted-foreground">Simulation Steps</div>
                <div className="font-mono">{namdConfig.simulationSteps.toLocaleString()}</div>
              </div>
              <div>
                <div className="text-muted-foreground">Temperature (K)</div>
                <div className="font-mono">{namdConfig.temperature}</div>
              </div>
              <div>
                <div className="text-muted-foreground">Timestep (fs)</div>
                <div className="font-mono">{namdConfig.timestep}</div>
              </div>
              <div>
                <div className="text-muted-foreground">Output Name</div>
                <div className="font-mono">{namdConfig.outputName}</div>
              </div>
              <div>
                <div className="text-muted-foreground">DCD Frequency</div>
                <div className="font-mono">{namdConfig.dcdFreq.toLocaleString()}</div>
              </div>
              <div>
                <div className="text-muted-foreground">Restart Frequency</div>
                <div className="font-mono">{namdConfig.restartFreq.toLocaleString()}</div>
              </div>
            </div>
          </div>

          {/* Input Files */}
          <div>
            <h4 className="font-medium mb-3">Input Files</h4>
            <div className="space-y-2 text-sm">
              <div>
                <span className="text-muted-foreground">Coordinates:</span> 
                <span className="ml-2 font-mono">{namdConfig.coordinates}</span>
              </div>
              <div>
                <span className="text-muted-foreground">Structure:</span> 
                <span className="ml-2 font-mono">{namdConfig.structure}</span>
              </div>
              <div>
                <span className="text-muted-foreground">Parameters:</span>
                <div className="ml-2 mt-1 flex flex-wrap gap-2">
                  {namdConfig.parameters.map((param, index) => (
                    <Badge key={index} variant="secondary" className="font-mono text-xs">
                      {param}
                    </Badge>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Force Field & Cutoffs */}
          <div>
            <h4 className="font-medium mb-3">Force Field & Cutoffs</h4>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4 text-sm">
              <div>
                <div className="text-muted-foreground">Cutoff (Å)</div>
                <div className="font-mono">{namdConfig.cutoff}</div>
              </div>
              <div>
                <div className="text-muted-foreground">Switch Distance (Å)</div>
                <div className="font-mono">{namdConfig.switchDist}</div>
              </div>
              <div>
                <div className="text-muted-foreground">Pairlist Distance (Å)</div>
                <div className="font-mono">{namdConfig.pairlistDist}</div>
              </div>
              <div>
                <div className="text-muted-foreground">PME</div>
                <Badge variant={namdConfig.PME ? "default" : "secondary"}>
                  {namdConfig.PME ? "Enabled" : "Disabled"}
                </Badge>
              </div>
              <div>
                <div className="text-muted-foreground">PME Grid Spacing (Å)</div>
                <div className="font-mono">{namdConfig.PMEGridSpacing}</div>
              </div>
            </div>
          </div>

          {/* Dynamics Settings */}
          <div>
            <h4 className="font-medium mb-3">Dynamics Settings</h4>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4 text-sm">
              <div>
                <div className="text-muted-foreground">Langevin Dynamics</div>
                <Badge variant={namdConfig.langevin ? "default" : "secondary"}>
                  {namdConfig.langevin ? "Enabled" : "Disabled"}
                </Badge>
              </div>
              <div>
                <div className="text-muted-foreground">Langevin Damping</div>
                <div className="font-mono">{namdConfig.langevinDamping} ps⁻¹</div>
              </div>
              <div>
                <div className="text-muted-foreground">Langevin Temperature (K)</div>
                <div className="font-mono">{namdConfig.langevinTemp}</div>
              </div>
              <div>
                <div className="text-muted-foreground">Langevin Hydrogen</div>
                <Badge variant={namdConfig.langevinHydrogen ? "default" : "secondary"}>
                  {namdConfig.langevinHydrogen ? "Enabled" : "Disabled"}
                </Badge>
              </div>
            </div>
          </div>

          {/* Pressure Control */}
          <div>
            <h4 className="font-medium mb-3">Pressure Control</h4>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4 text-sm">
              <div>
                <div className="text-muted-foreground">Langevin Piston</div>
                <Badge variant={namdConfig.langevinPiston ? "default" : "secondary"}>
                  {namdConfig.langevinPiston ? "Enabled" : "Disabled"}
                </Badge>
              </div>
              <div>
                <div className="text-muted-foreground">Target Pressure (bar)</div>
                <div className="font-mono">{namdConfig.langevinPistonTarget}</div>
              </div>
              <div>
                <div className="text-muted-foreground">Piston Period (fs)</div>
                <div className="font-mono">{namdConfig.langevinPistonPeriod}</div>
              </div>
              <div>
                <div className="text-muted-foreground">Piston Decay (fs)</div>
                <div className="font-mono">{namdConfig.langevinPistonDecay}</div>
              </div>
              <div>
                <div className="text-muted-foreground">Piston Temperature (K)</div>
                <div className="font-mono">{namdConfig.langevinPistonTemp}</div>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* SLURM Configuration */}
      <Card>
        <CardHeader>
          <CardTitle>SLURM Resource Allocation</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4 text-sm">
            <div>
              <div className="text-muted-foreground">Cores</div>
              <div className="font-mono">{slurmConfig.cores}</div>
            </div>
            <div>
              <div className="text-muted-foreground">Memory</div>
              <div className="font-mono">{slurmConfig.memory}</div>
            </div>
            <div>
              <div className="text-muted-foreground">Wall Time</div>
              <div className="font-mono">{slurmConfig.wallTime}</div>
            </div>
            <div>
              <div className="text-muted-foreground">Partition</div>
              <div className="font-mono">{slurmConfig.partition}</div>
            </div>
            <div>
              <div className="text-muted-foreground">QOS</div>
              <div className="font-mono">{slurmConfig.qos}</div>
            </div>
            <div>
              <div className="text-muted-foreground">Account</div>
              <div className="font-mono">{slurmConfig.account}</div>
            </div>
            <div>
              <div className="text-muted-foreground">Nodes</div>
              <div className="font-mono">{slurmConfig.nodes}</div>
            </div>
            <div>
              <div className="text-muted-foreground">Tasks per Node</div>
              <div className="font-mono">{slurmConfig.tasksPerNode}</div>
            </div>
            <div>
              <div className="text-muted-foreground">CPUs per Task</div>
              <div className="font-mono">{slurmConfig.cpusPerTask}</div>
            </div>
            <div>
              <div className="text-muted-foreground">GPUs</div>
              <div className="font-mono">{slurmConfig.gpus} × {slurmConfig.gpuType.toUpperCase()}</div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
